# Generated by Django 4.1.5 on 2023-01-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Payment pending"),
                            ("PAID", "Payment paid"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Type Payment"), ("FINE", "Type Fine")],
                        max_length=15,
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=63, unique=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
