# Generated by Django 4.1.5 on 2023-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
