# Generated by Django 4.1.5 on 2023-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=256)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard cover"), ("SOFT", "Soft cover")],
                        max_length=15,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
